### ISSUE TITLE
이미 가입된 이메일을 회원가입 로직에 사용할 시 사소한 이슈가 있습니다.

### ISSUE THREAD

**Issue by uuuuuuuk** [TeamMiso/Miso_Android_v2#151]
## 📌 개요
- 이미 가입된 이메일을 회원가입의 이메일 기입창에서 입력하고 회원가입 버튼을 누르면 우선적으로 인증번호 화면으로 넘어가지만 실제로는 서버에서 검증하고 있는 중복 처리에 관한 Exception이 발생해 이메일로 인증번호가 전송되지 않습니다. 따라서 회원가입 버튼을 누를 때 예외 검사를 우선적으로 진행하고 성공 2xx 을 받을 시에 인증번호 화면으로 넘어가는 로직으로 변경하면 좋을 것 같습니다..!!

## 📚 레퍼런스 (또는 새로 알게 된 내용) 혹은 궁금한 사항들
- 참고할 사항이 있다면 적어주세요.

**Comment by diejdkll** [comment]
제가 처리 할게여
